# Generated by Django 3.2.25 on 2025-01-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurassichack', '0006_auto_20250110_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_answer',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
