# Generated by Django 3.2.25 on 2025-01-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurassichack', '0007_alter_answer_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='next_question',
        ),
        migrations.AddField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='jurassichack.question'),
        ),
    ]
