# Generated by Django 3.2.25 on 2025-01-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurassichack', '0008_auto_20250110_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
